# Generated by Django 2.2.3 on 2019-08-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='redalert',
            field=models.BooleanField(default=False, verbose_name='Water is low'),
        ),
    ]
