# Generated by Django 2.2.3 on 2019-08-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_plant_redalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='moisture',
            field=models.CharField(default='098;094;092;090;082;080;064;060;098;094;092;090;082;080;064;060;098;094;092;090;082;080;064;060', max_length=100),
        ),
    ]
