# Generated by Django 2.2.3 on 2019-08-16 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190812_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='schedule',
        ),
        migrations.AddField(
            model_name='plant',
            name='schedule_freq',
            field=models.CharField(choices=[('1', 'day'), ('2', '2 days'), ('3', '3 days'), ('4', '4 days'), ('5', '5 days'), ('6', '6 days'), ('week', 'week'), ('2week', '2 weeks'), ('3week', '3 weeks'), ('month', 'month'), ('2month', '2 months')], default='1', max_length=3, verbose_name='Scheduled watering frequency'),
        ),
        migrations.AddField(
            model_name='plant',
            name='schedule_start',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3, verbose_name='Scheduled watering start'),
        ),
        migrations.AddField(
            model_name='plant',
            name='schedule_time',
            field=models.TimeField(default=datetime.datetime(2019, 8, 16, 12, 9, 17, 969381), verbose_name='Scheduled watering time of day'),
        ),
    ]
