# Generated by Django 2.2.3 on 2019-08-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190816_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='schedule_time',
            field=models.CharField(choices=[('1', '12:00am'), ('2', '12:30am'), ('3', '1:00am'), ('4', '1:30am'), ('5', '2:00am'), ('6', '2:30am'), ('7', '3:00am'), ('8', '3:30am'), ('9', '4:00am'), ('10', '4:30am'), ('11', '5:00am'), ('12', '5:30am'), ('13', '6:00am'), ('14', '6:30am'), ('15', '7:00am'), ('16', '7:30am'), ('17', '8:00am'), ('18', '8:30am'), ('19', '9:00am'), ('20', '9:30am'), ('21', '10:00am'), ('22', '10:30am'), ('23', '11:00am'), ('24', '11:30am'), ('25', '12:00pm'), ('26', '12:30pm'), ('27', '1:00pm'), ('28', '1:30pm'), ('29', '2:00pm'), ('30', '2:30pm'), ('31', '3:00pm'), ('32', '3:30pm'), ('33', '4:00pm'), ('34', '4:30pm'), ('35', '5:00pm'), ('36', '5:30pm'), ('37', '6:00pm'), ('38', '6:30pm'), ('39', '7:00pm'), ('40', '7:30pm'), ('41', '8:00pm'), ('42', '8:30pm'), ('43', '9:00pm'), ('44', '9:30pm'), ('45', '10:00pm'), ('46', '10:30pm'), ('47', '11:00pm'), ('48', '11:30pm')], default='19', max_length=2, verbose_name='Scheduled watering time'),
        ),
    ]
