# Generated by Django 2.2.3 on 2019-08-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190816_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='schedule_freq',
            field=models.CharField(choices=[('1', 'day'), ('2', 'other day'), ('week', 'week'), ('month', 'month from today')], default='1', max_length=3, verbose_name='Scheduled watering frequency'),
        ),
    ]
